const assert=require('assert');
const fs=require('fs');
const path=require('path');
const notebook=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../notebooks/MIE_Recognition_v0_3_Mobile_Colab.ipynb'),'utf8'));
const source=notebook.cells.flatMap(cell=>cell.source||[]).join('\n');
assert.equal(notebook.nbformat,4);
assert(source.includes("REF = 'codex/mie-generalization-v0.3.3'"));
assert(source.includes("MIE usará Python 3.10 aislado"));
assert(source.includes("requirements-colab-py310.txt"));
assert(source.includes("torch==2.2.2+cpu"));
assert(source.includes("from basic_pitch.inference import predict"));
assert(source.includes("checkout','--detach','FETCH_HEAD"));
assert(source.includes("Aplicar recuperación y contrato"));
assert(!source.includes("'pip','install','-q','-r','mie_core/requirements.txt'"));
assert(source.includes("files.upload()"));
assert(source.includes("resolve_event_octaves"));
assert(source.includes("apply_reasoning"));
assert(source.includes("MIE_RECOGNITION_MHT_v0_3_3.wav"));
assert(source.includes("MIE_RECOGNITION_v0_3_3.json"));
assert(source.includes("A · AUDIO DE ENTRADA"));
assert(source.includes("B · BASELINE MIE v0.3.2"));
assert(source.includes("C · CANDIDATO MIE v0.3.3: CONTINUIDAD + ARMONÍA PERSISTENTE"));
assert(source.includes("D · RECONSTRUCCIÓN FINAL v0.3.3"));
assert(source.includes("cross_track_generalization"));
assert(source.includes("recovered_candidate_count"));
assert(source.includes("files.download(package)"));
assert(source.includes("scientific_d_unlocked=false"));
console.log('MIE_MOBILE_COLAB_CONTRACT_PASS');
