const assert=require('assert');
const A=require('../app/prototype_v1/hook_composition_assistant.js');
const d0={schema:'D0',variants:[{variant:'thetic',events:Array(12).fill({})},{variant:'anacrustic',events:Array(10).fill({})},{variant:'syncopated',events:Array(11).fill({})}]};
const x=A.candidate({hook_id:'H1',language:'es',intention:'reencuentro',text_candidate:'vuelvo a ti\nsin mirar atrás',reference_sha256:'abc',reference_analysis:{tempo_bpm_median:96,beat_count:120,analysis_mode:'LOCAL'},d0_manifest:d0});
assert.equal(A.validate(x).status,'PASS');
assert.equal(x.generation_class,'D0_EXPLORATORY');
assert.equal(x.scientific_d_unlocked,false);
assert.equal(x.constraint_set.tempo_bpm,96);
assert.equal(x.constraint_set.melody_event_capacity,12);
assert.equal(x.prosody_status,'GENERATED_PROSODY_CANDIDATE');
assert.equal(x.required_next_gate,'PRODUCER_CURATES_SYLLABIFICATION_AND_STRESS');
assert.equal(A.candidate({}).status,'AUDIT_TEXT_REQUIRED');
const set=A.generateCandidates({hook_id:'H1',language:'es',intention:'reencuentro',reference_sha256:'abc',reference_analysis:{tempo_bpm_median:96,beat_count:120,analysis_mode:'LOCAL'},d0_manifest:d0},6);
assert.equal(set.status,'CANDIDATE_SET_READY_FOR_PRODUCER_CURATION');
assert.equal(set.candidates.length,6);
assert(set.candidates.every(c=>A.validate(c).status==='PASS'));
assert(set.candidates.every(c=>c.fit && Number.isFinite(c.fit.score)));
assert(set.candidates.every(c=>c.scientific_d_unlocked===false));
assert(set.candidates[0].fit.score>=set.candidates[1].fit.score);
console.log('HOOK_MULTIMODAL_COMPOSITION_ASSISTANT_PASS');