/* HookLab AI Coherence/Reasoning Layer v0.1
 * Contextual coherence gate. NOT a statistical trend engine.
 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HookLabAICoherence=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='hooklab-ai-coherence-reasoning-v0.1';
const PROMOTED='PROMOTE_TO_CONDITIONED_DEDUCTION';
function arr(x){return Array.isArray(x)?x:[];}
function txt(x){return String(x||'').trim();}
function tokens(s){return new Set(txt(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-z0-9ñ]+/).filter(x=>x.length>3));}
function overlap(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.min(A.size,B.size);}
function admissibleDeductions(xs){const used=[],excluded=[];for(const x of arr(xs)){if(x&&x.disposition===PROMOTED)used.push(x);else excluded.push({id:x&&x.id||null,reason:'NOT_PROMOTED'});}return{used,excluded};}
function state(input){const d=admissibleDeductions(input&&input.conditioned_deductions);return{schema:'HOOKLAB_AI_COHERENCE_STATE_v0.1',state_id:'AICS-'+Date.now(),session_id:input&&input.session_id||null,reference_audio_provenance:input&&input.reference_audio_provenance||null,promoted_conditioned_deductions:d.used,excluded_evidence:d.excluded,story_brief:input&&input.story_brief||null,narrative_state:input&&input.narrative_state||{},section_function:input&&input.section_function||null,section_intention:input&&input.section_intention||'',approved_sections:arr(input&&input.approved_sections),musical_constraints:input&&input.musical_constraints||null,prosodic_constraints:input&&input.prosodic_constraints||null};}
function audit(st,candidate){const prior=st.approved_sections.map(x=>x?.candidate?.plain_text||x?.text||'').filter(Boolean);const candidateText=candidate?.plain_text||candidate?.text||'';const maxRedundancy=prior.reduce((m,p)=>Math.max(m,overlap(candidateText,p)),0);const brief=[st.story_brief?.story,st.story_brief?.characters,st.story_brief?.relationship,st.story_brief?.conflict,st.story_brief?.key_scene,st.story_brief?.emotional_trajectory].filter(Boolean).join(' ');const briefAlignment=brief?overlap(candidateText,brief):null;const evidenceBoundary=st.excluded_evidence.length?'PASS_WITH_EXCLUSIONS':'PASS';const reasons=[];if(!st.story_brief)reasons.push('STORY_BRIEF_MISSING');if(!st.section_function)reasons.push('SECTION_FUNCTION_MISSING');if(maxRedundancy>=.75)reasons.push('HIGH_REDUNDANCY_WITH_APPROVED_SECTION');const disposition=evidenceBoundary!=='PASS'&&false?'AUDIT_EVIDENCE_BOUNDARY':reasons.length?'COHERENCE_REVISE':'COHERENCE_PASS';return{schema:'HOOKLAB_COHERENCE_AUDIT_v0.1',story_brief_alignment:briefAlignment,section_function_alignment:st.section_function?true:false,character_continuity:'REQUIRES_STRUCTURED_CHARACTER_STATE',point_of_view_continuity:'REQUIRES_STRUCTURED_POV_STATE',temporal_continuity:'REQUIRES_STRUCTURED_TEMPORAL_STATE',emotional_trajectory_continuity:'REQUIRES_STRUCTURED_EMOTIONAL_STATE',redundancy_with_approved_sections:maxRedundancy,open_thread_advancement:'REQUIRES_STRUCTURED_THREAD_STATE',lyric_prosody_compatibility:candidate?.prosody_status||'UNKNOWN',lyric_melody_capacity_compatibility:candidate?.fit?.melody_capacity_penalty===0?'PASS':'REVISE',evidence_boundary_status:evidenceBoundary,reasons,disposition};}
function evaluate(input,candidate){const st=state(input);const coherence=audit(st,candidate);return{schema:'HOOKLAB_AI_REASONING_OUTPUT_v0.1',ai_reasoning_layer_version:VERSION,input_state_id:st.state_id,evidence_ids_consumed:st.promoted_conditioned_deductions.map(x=>x.id).filter(Boolean),evidence_ids_excluded:st.excluded_evidence,story_brief_id:st.story_brief?.brief_id||null,target_section:st.section_function,prior_approved_section_ids:st.approved_sections.map(x=>x.section_id).filter(Boolean),coherence_audit:coherence,generation_constraints:{story_brief_required:true,section_metadata_must_not_become_lyric_token:true,promoted_evidence_only:true},forbidden_inferences:['SUCCESS_PREDICTION','CAUSALITY_FROM_ASSOCIATION','D0_TO_SCIENTIFIC_D','UNPROMOTED_EVIDENCE_USE'],candidate_realization_id:candidate?.text_candidate_id||candidate?.hook_id||null,human_evaluation_required:true};}
return{VERSION,PROMOTED,state,audit,evaluate};
});