/* HookLab Lyric Statistical Modeling Contract v0.1
 * Fail-closed registry for lyric/narrative features and analysis promotion.
 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HookLabLyricStats=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='hooklab-lyric-statistical-model-v0.1';
const REQUIRED_FEATURE=['feature_id','construct','analytic_layer','operational_definition','unit','provider','version','measurement_error','calibration','musical_relevance','research_question_enabled','outcome','population','confounders','forbidden_interpretations','provenance'];
const REQUIRED_ANALYSIS=['analysis_id','research_question','population_scope','outcome','admissible_feature_ids','primary_tests','covariates','multiplicity_family','effect_size_criterion','robustness_plan','replication_requirement','stop_promotion_rule'];
function missing(obj,keys){return keys.filter(k=>obj?.[k]==null||obj?.[k]===''||(Array.isArray(obj?.[k])&&!obj[k].length));}
function admitFeature(feature){const miss=missing(feature,REQUIRED_FEATURE);return{status:miss.length?'AUDIT_FEATURE_NOT_DEFINED':'FEATURE_ADMISSIBLE',missing:miss,feature_id:feature?.feature_id||null};}
function registerAnalysis(registry,featureMap){const miss=missing(registry,REQUIRED_ANALYSIS),bad=[];for(const id of registry?.admissible_feature_ids||[]){const gate=admitFeature(featureMap?.[id]);if(gate.status!=='FEATURE_ADMISSIBLE')bad.push({feature_id:id,gate});}return{status:miss.length||bad.length?'AUDIT_ANALYSIS_NOT_REGISTERED':'ANALYSIS_REGISTERED',missing:miss,inadmissible_features:bad,analysis_id:registry?.analysis_id||null};}
function disposition(result){if(!result)return'AUDIT';if(result.analysis_class==='exploratory'&&result.replication_status!=='REPLICATED')return'HOLD_FOR_REPLICATION';if(result.robustness_status!=='PASS')return'NO_PROMOTION';if(result.multiplicity_control_status!=='PASS')return'NO_PROMOTION';if(result.effect_size_status!=='MEETS_PREDECLARED_CRITERION')return'NO_PROMOTION';if(result.uncertainty_status!=='ACCEPTABLE')return'NO_PROMOTION';if(result.replication_required&&result.replication_status!=='REPLICATED')return'HOLD_FOR_REPLICATION';return'PROMOTE_TO_CONDITIONED_DEDUCTION';}
function finalize(result){const d=disposition(result);return{schema:'HOOKLAB_LYRIC_ANALYSIS_RESULT_v0.1',analysis_id:result?.analysis_id||null,population_scope:result?.population_scope||null,n_eligible:result?.n_eligible??null,effect_size_and_uncertainty:result?.effect_size_and_uncertainty||null,multiplicity_control:result?.multiplicity_control_status||null,robustness_sensitivity:result?.robustness_status||null,replication_status:result?.replication_status||null,theory_support:result?.theory_support||null,claim_level:result?.claim_level||null,disposition:d,data_says:result?.data_says||null,statistics_say:result?.statistics_say||null,theory_says:result?.theory_says||null,generation_tests:result?.generation_tests||null,producer_decides:result?.producer_decides||null};}
function promotedDeduction(result){const f=finalize(result);if(f.disposition!=='PROMOTE_TO_CONDITIONED_DEDUCTION')return{status:'BLOCKED',reason:f.disposition,result:f};return{status:'PASS',deduction:{id:'DED-'+f.analysis_id,disposition:f.disposition,claim_level:f.claim_level,condition:f.statistics_say,source_analysis_id:f.analysis_id,provenance:{model_version:VERSION}}};}
return{VERSION,REQUIRED_FEATURE,REQUIRED_ANALYSIS,admitFeature,registerAnalysis,finalize,promotedDeduction};
});