/* HookLab Lyric Statistical Modeling Contract v0.3
 * Fail-closed registry for lyric/narrative features and analysis promotion.
 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HookLabLyricStats=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='hooklab-lyric-statistical-model-v0.3';
const REQUIRED_FEATURE=['feature_id','inventory_class','construct','analytic_layer','operational_definition','unit','provider','version','measurement_error','calibration','textual_relevance','musical_relevance','research_question_enabled','outcome','population','confounders','forbidden_interpretations','provenance'];
const REQUIRED_ANALYSIS=['analysis_id','research_question','population_scope','outcome','admissible_feature_ids','primary_tests','covariates','multiplicity_family','effect_size_criterion','robustness_plan','replication_requirement','stop_promotion_rule','expected_direction','trend_origin_policy','human_trend_override_allowed','ai_trend_override_allowed','literature_sets_empirical_direction','producer_preference_used_as_evidence','source_revision','feature_registry_id'];
function missing(obj,keys){return keys.filter(k=>obj?.[k]==null||obj?.[k]===''||(Array.isArray(obj?.[k])&&!obj[k].length));}
function calibrationStatus(feature){return typeof feature?.calibration==='object'?feature.calibration.status:feature?.calibration;}
function unresolvedDependencies(feature){return (feature?.dependencies||[]).filter(x=>x&&x.status!=='READY'&&x.status!=='SATISFIED');}
function admitFeature(feature){
  const miss=missing(feature,REQUIRED_FEATURE);
  if(miss.length)return{status:'AUDIT_FEATURE_NOT_DEFINED',missing:miss,feature_id:feature?.feature_id||null};
  if(feature?.lifecycle_status==='FROZEN_NO_REPROCESS'&&feature?.new_evidence!==true)return{status:'FROZEN_NO_REPROCESS',missing:[],feature_id:feature.feature_id};
  if(['B_CANDIDATE_REQUIRES_OPERATIONALIZATION','E_NOT_YET_EXISTENT'].includes(feature.inventory_class))return{status:'AUDIT_FEATURE_NOT_DEFINED',missing:[],reason:'CANDIDATE_OR_MEASUREMENT_NOT_PRESENT_IN_DATA',feature_id:feature.feature_id};
  const deps=unresolvedDependencies(feature);
  if(deps.length)return{status:'AUDIT_FEATURE_DEPENDENCY_UNRESOLVED',missing:[],unresolved_dependencies:deps,feature_id:feature.feature_id};
  const calibration=calibrationStatus(feature);
  if(!['CALIBRATION_PASS','NOT_REQUIRED_JUSTIFIED'].includes(calibration))return{status:'AUDIT_FEATURE_NOT_CALIBRATED',missing:[],calibration_status:calibration||null,feature_id:feature.feature_id};
  return{status:'FEATURE_ADMISSIBLE',missing:[],feature_id:feature.feature_id};
}
function analysisBoundaryViolations(registry){const v=[];if(registry?.expected_direction!==null)v.push('EXPECTED_DIRECTION_MUST_BE_NULL');if(registry?.trend_origin_policy!=='REGISTERED_DATA_AND_STATISTICS_ONLY')v.push('INVALID_TREND_ORIGIN_POLICY');for(const k of['human_trend_override_allowed','ai_trend_override_allowed','literature_sets_empirical_direction','producer_preference_used_as_evidence'])if(registry?.[k]!==false)v.push(k.toUpperCase()+'_MUST_BE_FALSE');return v;}
function registerAnalysis(registry,featureMap){const miss=missing(registry,REQUIRED_ANALYSIS.filter(k=>k!=='expected_direction')),bad=[],violations=analysisBoundaryViolations(registry);if(!Object.prototype.hasOwnProperty.call(registry||{},'expected_direction'))miss.push('expected_direction');for(const id of registry?.admissible_feature_ids||[]){const gate=admitFeature(featureMap?.[id]);if(gate.status!=='FEATURE_ADMISSIBLE')bad.push({feature_id:id,gate});}return{status:miss.length||bad.length||violations.length?'AUDIT_ANALYSIS_NOT_REGISTERED':'ANALYSIS_REGISTERED',missing:miss,inadmissible_features:bad,boundary_violations:violations,analysis_id:registry?.analysis_id||null};}
function resultBoundaryViolations(result){const v=[];if(result?.computation_origin!=='REGISTERED_STATISTICAL_ENGINE')v.push('INVALID_COMPUTATION_ORIGIN');if(result?.trend_origin_policy!=='REGISTERED_DATA_AND_STATISTICS_ONLY')v.push('INVALID_TREND_ORIGIN_POLICY');for(const k of['human_trend_override_applied','ai_trend_override_applied','literature_direction_applied','producer_preference_applied'])if(result?.[k]!==false)v.push(k.toUpperCase()+'_MUST_BE_FALSE');if(!result?.registration_hash_sha256)v.push('MISSING_REGISTRATION_HASH');if(!result?.normalized_input_hash_sha256)v.push('MISSING_INPUT_HASH');if(!result?.engine_version)v.push('MISSING_ENGINE_VERSION');return v;}
function disposition(result){if(!result||resultBoundaryViolations(result).length)return'AUDIT';if(result.analysis_class==='exploratory'&&result.replication_status!=='REPLICATED')return'HOLD_FOR_REPLICATION';if(result.robustness_status!=='PASS')return'NO_PROMOTION';if(result.multiplicity_control_status!=='PASS')return'NO_PROMOTION';if(result.effect_size_status!=='MEETS_PREDECLARED_CRITERION')return'NO_PROMOTION';if(result.uncertainty_status!=='ACCEPTABLE')return'NO_PROMOTION';if(result.replication_required&&result.replication_status!=='REPLICATED')return'HOLD_FOR_REPLICATION';return'PROMOTE_TO_CONDITIONED_DEDUCTION';}
function finalize(result){const d=disposition(result);return{schema:'HOOKLAB_LYRIC_ANALYSIS_RESULT_v0.2',analysis_id:result?.analysis_id||null,population_scope:result?.population_scope||null,n_eligible:result?.n_eligible??null,effect_size_and_uncertainty:result?.effect_size_and_uncertainty||null,multiplicity_control:result?.multiplicity_control_status||null,robustness_sensitivity:result?.robustness_status||null,replication_status:result?.replication_status||null,theory_support:result?.theory_support||null,claim_level:result?.claim_level||null,disposition:d,boundary_violations:resultBoundaryViolations(result),computation_origin:result?.computation_origin||null,trend_origin_policy:result?.trend_origin_policy||null,registration_hash_sha256:result?.registration_hash_sha256||null,normalized_input_hash_sha256:result?.normalized_input_hash_sha256||null,engine_version:result?.engine_version||null,data_says:result?.data_says||null,statistics_say:result?.statistics_say||null,theory_says:result?.theory_says||null,generation_tests:result?.generation_tests||null,producer_decides:result?.producer_decides||null};}
function promotedDeduction(result){const f=finalize(result);if(f.disposition!=='PROMOTE_TO_CONDITIONED_DEDUCTION')return{status:'BLOCKED',reason:f.disposition,result:f};return{status:'PASS',deduction:{id:'DED-'+f.analysis_id,disposition:f.disposition,claim_level:f.claim_level,condition:f.statistics_say,source_analysis_id:f.analysis_id,provenance:{model_version:VERSION}}};}
function auditRegistry(registry){const features=Array.isArray(registry?.features)?registry.features:[];const items=features.map(feature=>({feature_id:feature?.feature_id||null,...admitFeature(feature)}));const counts=items.reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{});return{schema:'HOOKLAB_LYRIC_FEATURE_REGISTRY_AUDIT_v0.1',registry_id:registry?.registry_id||null,total_features:items.length,counts,analysis_registration_unlocked:counts.FEATURE_ADMISSIBLE>0,items};}
return{VERSION,REQUIRED_FEATURE,REQUIRED_ANALYSIS,admitFeature,auditRegistry,analysisBoundaryViolations,registerAnalysis,resultBoundaryViolations,finalize,promotedDeduction};
});
